<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="jest tests" tests="11" failures="2" errors="0" time="5.207">
  <testsuite name="User routes" errors="0" failures="0" skipped="0" timestamp="2024-02-26T23:32:33" time="4.209" tests="3">
    <testcase classname="User routes POST /user/create should create a new user" name="User routes POST /user/create should create a new user" time="0.118">
    </testcase>
    <testcase classname="User routes POST /user/create should send back a conflict error" name="User routes POST /user/create should send back a conflict error" time="0.004">
    </testcase>
    <testcase classname="User routes POST /user/create should send back a bad request error" name="User routes POST /user/create should send back a bad request error" time="0.003">
    </testcase>
  </testsuite>
  <testsuite name="activity creation" errors="0" failures="2" skipped="0" timestamp="2024-02-26T23:32:33" time="4.275" tests="2">
    <testcase classname="activity creation should create a new user" name="activity creation should create a new user" time="0.003">
      <failure>Error: Unknown column &apos;users.id&apos; in &apos;where clause&apos;
    at PromisePool.query (/Users/Marc-Antoine/Documents/Dev/INM5151_dev/creation-db-planned-activity2/touristes-de-salon-expires/backend/node_modules/mysql2/promise.js:356:22)
    at MySql2PreparedQuery.execute (/Users/Marc-Antoine/Documents/Dev/INM5151_dev/creation-db-planned-activity2/touristes-de-salon-expires/backend/node_modules/src/mysql2/session.ts:85:18)
    at QueryPromise.execute (/Users/Marc-Antoine/Documents/Dev/INM5151_dev/creation-db-planned-activity2/touristes-de-salon-expires/backend/node_modules/src/mysql-core/query-builders/delete.ts:152:25)
    at QueryPromise.then (/Users/Marc-Antoine/Documents/Dev/INM5151_dev/creation-db-planned-activity2/touristes-de-salon-expires/backend/node_modules/src/query-promise.ts:31:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)</failure>
    </testcase>
    <testcase classname="activity creation should create a new activity in the database" name="activity creation should create a new activity in the database" time="0">
      <failure>Error: Unknown column &apos;users.id&apos; in &apos;where clause&apos;
    at PromisePool.query (/Users/Marc-Antoine/Documents/Dev/INM5151_dev/creation-db-planned-activity2/touristes-de-salon-expires/backend/node_modules/mysql2/promise.js:356:22)
    at MySql2PreparedQuery.execute (/Users/Marc-Antoine/Documents/Dev/INM5151_dev/creation-db-planned-activity2/touristes-de-salon-expires/backend/node_modules/src/mysql2/session.ts:85:18)
    at QueryPromise.execute (/Users/Marc-Antoine/Documents/Dev/INM5151_dev/creation-db-planned-activity2/touristes-de-salon-expires/backend/node_modules/src/mysql-core/query-builders/delete.ts:152:25)
    at QueryPromise.then (/Users/Marc-Antoine/Documents/Dev/INM5151_dev/creation-db-planned-activity2/touristes-de-salon-expires/backend/node_modules/src/query-promise.ts:31:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)</failure>
    </testcase>
    <testcase classname=" Test execution failure: could be caused by test hooks like &apos;afterAll&apos;." name=" Test execution failure: could be caused by test hooks like &apos;afterAll&apos;." time="0">
      <failure>{&quot;message&quot;:&quot;&quot;,&quot;stack&quot;:&quot;Error: Unknown column &apos;users.id&apos; in &apos;where clause&apos;\n    at PromisePool.query (/Users/Marc-Antoine/Documents/Dev/INM5151_dev/creation-db-planned-activity2/touristes-de-salon-expires/backend/node_modules/mysql2/promise.js:356:22)\n    at MySql2PreparedQuery.execute (/Users/Marc-Antoine/Documents/Dev/INM5151_dev/creation-db-planned-activity2/touristes-de-salon-expires/backend/node_modules/src/mysql2/session.ts:85:18)\n    at QueryPromise.execute (/Users/Marc-Antoine/Documents/Dev/INM5151_dev/creation-db-planned-activity2/touristes-de-salon-expires/backend/node_modules/src/mysql-core/query-builders/delete.ts:152:25)\n    at QueryPromise.then (/Users/Marc-Antoine/Documents/Dev/INM5151_dev/creation-db-planned-activity2/touristes-de-salon-expires/backend/node_modules/src/query-promise.ts:31:15)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)&quot;}</failure>
    </testcase>
  </testsuite>
  <testsuite name="POST /auth" errors="0" failures="0" skipped="0" timestamp="2024-02-26T23:32:33" time="4.388" tests="4">
    <testcase classname="POST /auth Succesfully returns a token" name="POST /auth Succesfully returns a token" time="0.278">
    </testcase>
    <testcase classname="POST /auth credentials error when invalid name" name="POST /auth credentials error when invalid name" time="0.004">
    </testcase>
    <testcase classname="POST /auth credentials error when invalid password" name="POST /auth credentials error when invalid password" time="0.002">
    </testcase>
    <testcase classname="POST /auth should send back a bad request error" name="POST /auth should send back a bad request error" time="0.003">
    </testcase>
  </testsuite>
  <testsuite name="POST /auth" errors="0" failures="0" skipped="0" timestamp="2024-02-26T23:32:33" time="4.402" tests="2">
    <testcase classname="POST /auth Succesfully authenticate a user" name="POST /auth Succesfully authenticate a user" time="0.28">
    </testcase>
    <testcase classname="POST /auth Sould send an unauthorize response" name="POST /auth Sould send an unauthorize response" time="0.002">
    </testcase>
  </testsuite>
</testsuites>